version: '2'
services:
  alertservice-app:
    image: alertservice
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://alertservice-postgresql:5432/alertservice
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
  alertservice-postgresql:
    extends:
      file: postgresql.yml
      service: alertservice-postgresql
